before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: xTFBdVixcEdXJ6z9jvs4KgNI85IUPRGDk3owlKChNeJYuUY9sYInxiwUdAsYQ4Qu8+vTWk41K0Z2H8eMfhQ8/QWKv7XDE+zWpdVTLLJUXQaGUMttpqpo8I9s7Y6uoEUa2WgaGwP3OaUd39xGKee0Gw+dXX1TJrE6DUZnz6tQ4VRee3mEio0dCJOgjTQhhbqXKN3M7VcUPqrVdcHfiPEAIoezxf45fDeUmj7pLozo+Acccik8qxhvcNzKk/C7bdsB50k7iVWih6sGFgE951xU5JIb0I22rmEl+IZRTF3OExb17ybj5VuM9eaV56A2QYddRKprrMxdL9JkyUO+LE4WLdLDMwQug8RTUdj0tsraqEHezpBJqvfIF5yvFoLaCnTuGHRw4Ew2Q3PK12K+O8lYMAK8GqY1mip2ZXTrLSyL+tHwLSm3CD0UM9cT31ifh7m/zE/pDCcP7Pf9s3jRqeOW2JqZy62erNrd0ABRDvHHWHKrBkFlXZpSOjIA2VyI4umyLDU1Tgaw98swQ3bQRakxSAFvEtH8+pLxL6tkNN2DcqQ44JSAFNCVtLphSi54SLou5tDfouxAInmh/KZthr08RGYQ2C7fAtbv1Zmt4GDA17iCJDyENtXuW1YF9Ca8mWjyj0YZHm1thowxW99bcl6pYSWmiC1OXGxvvGNUCUiCCIo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
